### ISSUE TITLE
plugin fails with streamlink 6.4.2

### ISSUE THREAD

**Issue by matteoguglielmi** [nonvegan/streamlink-plugin-kick#10]
After installing the latest streamlink version available (as of today, streamlink-6.4.2-py3-none-any.whl) the kick plugin stopped working

```
[cli][info] Found matching plugin kick for URL kick.com/highemissions
error: No playable streams found on this URL: kick.com/highemissions
```

plugin is found but the stream is not played.

Thank you.

**Comment by Taramur** [comment]
I still have 5.5.1. I also get this error sometimes. Just trying the command a few times will start the stream.

**Comment by matteoguglielmi** [comment]
> I still have 5.5.1. I also get this error sometimes. Just trying the command a few times will start the stream.

I noticed that as well.

Thank you!

**Comment by nonvegan** [comment]
Can you please run streamlink with  `--loglevel debug`, and paste the output?

**Comment by aiyulu1** [comment]
> Can you please run streamlink with `--loglevel debug`, and paste the output?

streamlink https://kick.com/yourrage best -o 2024-03-02.mp4 --loglevel debug
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.15.0-89-generic-x86_64-with-glibc2.35
[cli][debug] Python:     3.10.12
[cli][debug] OpenSSL:    OpenSSL 3.0.2 15 Mar 2022
[cli][debug] Streamlink: 6.4.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2020.6.20
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.19.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.23.1
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.8.0
[cli][debug]  urllib3: 1.26.5
[cli][debug]  websocket-client: 1.6.4
[cli][debug] Arguments:
[cli][debug]  url=https://kick.com/yourrage
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=2024-03-02.mp4
[cli][info] Found matching plugin kick for URL https://kick.com/yourrage
[plugins.kick][debug] Unable to validate result: ValidationError:
  Unable to parse JSON: Expecting value: line 1 column 1 (char 0) (\'\<!DOCTYPE html>\<html lang="en-US"> ...)
error: No playable streams found on this URL: https://kick.com/yourrage

**Comment by nonvegan** [comment]
The request is hitting the cloudflare anti-bot page, so it's unable to get the the api JSON response and it tries to parse the HTML page

**Comment by aiyulu1** [comment]
> The request is hitting the cloudflare anti-bot page, so it's unable to get the the api JSON response and it tries to parse the HTML page

er, they work now
