### ISSUE TITLE
no module named cloudscraper

### ISSUE THREAD

**Issue by kai933** [nonvegan/streamlink-plugin-kick#2]
Hi im totally new to such thinks, github etc..
using win10
i installed python, streamlink and then cloudscraper with this pip command

but if i try to start a kick stream im getting only this:

[session][error] Failed to load plugin kick from C:\Users\xxx\AppData\Roaming\streamlink\plugins
Traceback (most recent call last):
  File "C:\Program Files\Streamlink\pkgs\streamlink\session.py", line 617, in load_plugins
    mod = load_module(module_name, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Streamlink\pkgs\streamlink\utils\module.py", line 14, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\xxx\AppData\Roaming\streamlink\plugins\kick.py", line 8, in <module>
    import cloudscraper
ModuleNotFoundError: No module named 'cloudscraper'

help pls

**Comment by kai933** [comment]
tried several times, brings nothing =/

$ pip install cloudscraper
Requirement already satisfied: cloudscraper in c:\users\tobias\appdata\local\programs\python\python311\lib\site-packages (1.2.69)
Requirement already satisfied: pyparsing>=2.4.7 in c:\users\tobias\appdata\local\programs\python\python311\lib\site-packages (from cloudscraper) (3.0.9)
Requirement already satisfied: requests>=2.9.2 in c:\users\tobias\appdata\local\programs\python\python311\lib\site-packages (from cloudscraper) (2.27.1)
Requirement already satisfied: requests-toolbelt>=0.9.1 in c:\users\tobias\appdata\local\programs\python\python311\lib\site-packages (from cloudscraper) (0.10.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\tobias\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.9.2->cloudscraper) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tobias\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.9.2->cloudscraper) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\tobias\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.9.2->cloudscraper) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in c:\users\tobias\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.9.2->cloudscraper) (3.4)

**Comment by nonvegan** [comment]
I'm sorry but I'm not sure what the issue could be, perhaps you could try to install it inside a [virtual environment](https://docs.python.org/3/library/venv.html) and see if that works. I just tested it with python v3.10.5 and it worked.

**Comment by nonvegan** [comment]
Hey @kai933 I think we figured out your problem over at issue [#3](https://github.com/nonvegan/streamlink-plugin-kick/issues/3#issuecomment-1496280946), take a look.

**Comment by kai933** [comment]
ah cool, yes that solved the problem. interesting that the streamlink windows builds have their own python packages.

thanks for the help
