### ISSUE TITLE
Plugin can't handle hyphen in URL.

### ISSUE THREAD

**Issue by GitNerror** [nonvegan/streamlink-plugin-kick#5]
Kick users can use '-' in their names, like xxxxxxxx-xxx, and I get the following error message for those:

`error: No plugin can handle URL: https://kick.com/xxxxxxxx-xxx`

Otherwise the plugin works well :)

**Comment by nonvegan** [comment]
Should be fixed now. Can you check?

**Comment by GitNerror** [comment]
Yup, that did the trick, thanks :)

**Comment by nonvegan** [comment]
Nice, thank you.
