### ISSUE TITLE
connections not closed

### ISSUE THREAD

**Issue by ffbw4hwj** [nonvegan/streamlink-plugin-kick#6]
when streamlink is in retry mode, new cloudscraper connections keep getting created and old ones not destroyed
eventually it reaches windows max limit and causes the whole windows session to unable to open new tcpip connections

**Comment by nonvegan** [comment]
My advice is not use retry mode while using this plugin then. Or is there something else that can be done?

**Comment by nonvegan** [comment]
Did some digging and came up with 7ecf5a1e3a36e546a1f0d215051c2063377982fe. Let me know if this fixes it 🙂

**Comment by ffbw4hwj** [comment]
problem solved! thx for the quick fix
