### ISSUE TITLE
No way to avoid the Cloudflare Captcha challenge now

### ISSUE THREAD

**Issue by GitNerror** [nonvegan/streamlink-plugin-kick#7]
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

It completely stopped working yesterday. Normally I am able to switch VPN server or just turn off the VPN and get past that error message anyway. No more. I've tried all the countries and rebooted and such, and waited a day to no avail. Streamlink still works fine for twitch so I expect Kick have either detected streamlink with the kick plugin and blocked that somehow, or it's specific to my PC. MAC address? That shouldn't be sent to them though.

**Comment by nat-om** [comment]
It's working currently. It seems to only happen when Kick is having issues (E.g. buffering).

**Comment by GitNerror** [comment]
Ah yes it works for me again now. Thanks. Feel free to close this one if you like.
